# MA 3236 Computer Assignment - Jiasheng Zhou

## 1.

For a function in quadratic form $q(w) = \frac12x^TQx+b^Tx+c$, $q(w)$ is conve\:X iff $Q$ is PSD, and is strictly conve\:X when $Q$ is PD. e\:Xpanding $f(w)$:
$$
\begin{align}
f(w) &= \frac12||(e\:X)w-y||^2 \\
&= \frac12((e\:X)w-y)^T((e\:X)w-y) \\
&= \frac12(w^T(e\:X)^T-y^T)((e\:X)w-y) \\
&= \frac12(w^T(e\:X)^T(e\:X)w) -y^T(e\:X)w +\frac12y^Ty.
\end{align}
$$
As $w^T(e\:X)^T(e\:X)w = ((e\:X)w)^T((e\:X)w) = ||(e\:X)w||^2 \geq 0$, $\forall w \in \mathbb{R}^{p+1}$, $Q=(e\:X)^T(e\:X)$ is PSD and thus $f(w)$ is conve\:X.

To ensure $Q$ is PD, we would need $((e\:X)w)^T((e\:X)w) = ||(e\:X)w||^2 > 0$ for all $w \neq 0$. This requirement is the definition of linear independence, so we must have $e\:X$ be linearly independent. This occurs when $X$ is linearly independent and $e$ is not a linear combination of the columns of $X$. 

It is almost certain that the wine dataset satisfies this condition. As there is a positive amount of variance with the values for each column, it isn't possible that one entire column is constant (multiple of $e$). Moreover, it is e\:Xtremely unlikely that there is a linear combination of columns that results in a constant column, since each value's range is continuous, and there are over 4000 observations. 

## 2.

Let $t_k$ be step size at $k$th iteration. Then

$$
\begin{align}
t_k &= \text{arg min}_t(f(w^{(k)}-t\nabla_k) \\
&= \text{arg min}_t(\frac12||(e\:X)w^{(k)}-y-t(e\:X)\nabla_k||^2)
\end{align}
$$

To find the minimum, we take the derivative of $f$ w.r.t. to $t$ and find the zeros:
$$
\begin{align}
0 &= \frac{d}{dt}(\frac12||(e\:X)w^{(k)}-y-t(e\:X)\nabla_k||^2) \\
&= ((e\:X)w^{(k)}-y-t(e\:X)\nabla_k)^T((e\:X)\nabla_k) \\
\end{align}
$$
Solving,
$$
\begin{align}
t((e\:X)\nabla_k)^T(e\:X)\nabla_k &= ((e\:X)w^{(k)}-y)^T(e\:X)\nabla_k \\
t\nabla_k^T(e\:X)^T(e\:X)\nabla_k &= ((e\:X)^T((e\:X)w^{(k)}-y))^T\nabla_k \\
t &= \frac{(\nabla_k)^T\nabla_k}{\nabla_k^T(e\:X)^T(e\:X)\nabla_k}
\end{align}
$$
To arrive at the final line above, note that $\nabla_k = (e\:X)^T(e\:X)w^{(k)}-(e\:X)^Ty$, which we substitute into the numerator.

## 3.

note: I couldn't find the preprocessed files mentioned on the assignment writeup on Canvas (Xytrain.csv, Xytest.csv) so I downloaded the dataset directly from the link provided

In [54]:
import numpy as np
import time

data = np.loadtxt("winequality-white.csv", delimiter=';', skiprows=1)
X = data[:, :-1]
y = data[:, -1:].reshape(-1, 1)

X_train, X_test = X[:4298], X[4298:]
y_train, y_test = y[:4298], y[4298:]

In [55]:
n, p = X_train.shape
e = np.ones((n, 1))
eX = np.hstack([e, X_train])

w = np.zeros((p + 1, 1))
tolerance = 1e-6
iter = 5000

In [74]:
print("\n    iter     w[0]         w[1]       ||grad||      step-len")
print("-------------------------------------------------------------")
start = time.time()
for i in range(iter):
    r = eX @ w - y_train
    fun = 0.5 * float(r.T @ r)
    grad = eX.T @ r
    d = -grad
    normd = np.linalg.norm(d)
    print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
    if(np.linalg.norm(grad) < tolerance):
        break
    t = float((grad.T @ grad) / (grad.T @ eX.T @ eX @ grad))
    print(f"   {t:11.6f}")
    w = w + t*d
end = time.time()
w_star = w
runtime = end-start


    iter     w[0]         w[1]       ||grad||      step-len
-------------------------------------------------------------
       0    0.129175   -0.023644    5.629e+02      0.000000
       1    0.129175   -0.023644    6.536e+01      0.000001
       2    0.129180   -0.023646    5.627e+02      0.000000
       3    0.129181   -0.023645    6.534e+01      0.000001
       4    0.129186   -0.023647    5.626e+02      0.000000
       5    0.129186   -0.023647    6.532e+01      0.000001
       6    0.129192   -0.023649    5.624e+02      0.000000
       7    0.129192   -0.023649    6.530e+01      0.000001
       8    0.129197   -0.023651    5.623e+02      0.000000
       9    0.129197   -0.023651    6.529e+01      0.000001
      10    0.129203   -0.023653    5.621e+02      0.000000
      11    0.129203   -0.023653    6.527e+01      0.000001
      12    0.129208   -0.023655    5.620e+02      0.000000
      13    0.129208   -0.023655    6.526e+01      0.000001
      14    0.129214   -0.023657    5

C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\2292579676.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun = 0.5 * float(r.T @ r)
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\2292579676.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\2292579676.py:13: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  t = float((grad.T @ gr

     108    0.129466   -0.023787    5.599e+02      0.000000
     109    0.129466   -0.023787    6.502e+01      0.000001
     110    0.129472   -0.023790    5.599e+02      0.000000
     111    0.129472   -0.023790    6.502e+01      0.000001
     112    0.129477   -0.023793    5.599e+02      0.000000
     113    0.129477   -0.023793    6.501e+01      0.000001
     114    0.129482   -0.023796    5.599e+02      0.000000
     115    0.129482   -0.023796    6.501e+01      0.000001
     116    0.129488   -0.023799    5.598e+02      0.000000
     117    0.129488   -0.023799    6.501e+01      0.000001
     118    0.129493   -0.023802    5.598e+02      0.000000
     119    0.129493   -0.023802    6.500e+01      0.000001
     120    0.129498   -0.023805    5.598e+02      0.000000
     121    0.129498   -0.023804    6.500e+01      0.000001
     122    0.129504   -0.023808    5.597e+02      0.000000
     123    0.129504   -0.023807    6.500e+01      0.000001
     124    0.129509   -0.023811    5.59

In [75]:
w_star

array([[ 0.14084551],
       [-0.02765858],
       [-0.54857649],
       [ 0.05841667],
       [ 0.02381487],
       [-0.00903644],
       [ 0.0079424 ],
       [-0.00152716],
       [ 0.13822797],
       [ 0.48521744],
       [ 0.24723779],
       [ 0.38507815]])

In [76]:
r_final = eX @ w_star - y_train
fun_final = 0.5 * float(r_final.T @ r_final)
grad_final = eX.T @ r_final
norm_final = np.linalg.norm(grad_final)

C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\417156451.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun_final = 0.5 * float(r_final.T @ r_final)


In [77]:
Q = eX.T @ eX
eigvals = np.linalg.eigvalsh(Q)
kappa = eigvals.max() / eigvals.min()
rho = ((kappa-1)/(kappa+1))**2

In [78]:
w_star, rho, f"{runtime:.4f}", f"{fun_final:.4f}", f"{norm_final:.4f}"

(array([[ 0.14084551],
        [-0.02765858],
        [-0.54857649],
        [ 0.05841667],
        [ 0.02381487],
        [-0.00903644],
        [ 0.0079424 ],
        [-0.00152716],
        [ 0.13822797],
        [ 0.48521744],
        [ 0.24723779],
        [ 0.38507815]]),
 0.9999999999701643,
 '8.3146',
 '1290.0264',
 '501.3546')

In [79]:
y_pred_train = eX @ w_star

eX_test = np.hstack([np.ones((X_test.shape[0], 1)), X_test])
y_pred_test = eX_test @ w_star

mae_train = np.mean(np.abs(y_train - y_pred_train))
mae_test = np.mean(np.abs(y_test - y_pred_test))
mae_train, mae_test

(0.6060067077543982, 0.5553643234950328)

## 4.

In [68]:
l = 5
I = np.eye(p+1)

print("\n    iter     w[0]         w[1]       ||grad||      step-len")
print("-------------------------------------------------------------")
start = time.time()
for i in range(iter):
    r = eX @ w - y_train
    fun = 0.5 * float(r.T @ r) + l*float(w.T @ w)
    grad = eX.T @ r + 2*l*w
    d = -grad
    normd = np.linalg.norm(d)
    print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
    if(np.linalg.norm(grad) < tolerance):
        break
    t = float((grad.T @ grad) / (grad.T @ (eX.T @ eX + 2.0 *l * I) @ grad))
    print(f"   {t:11.6f}")
    w = w + t*d
end = time.time()
w_star_l2 = w
runtime_l2 = end-start


    iter     w[0]         w[1]       ||grad||      step-len
-------------------------------------------------------------
       0    0.111923   -0.017287    6.919e+02      0.000000
       1    0.111923   -0.017287    7.306e+01      0.000001
       2    0.111932   -0.017291    6.919e+02      0.000000
       3    0.111932   -0.017290    7.305e+01      0.000001
       4    0.111941   -0.017294    6.918e+02      0.000000
       5    0.111941   -0.017294    7.305e+01      0.000001
       6    0.111949   -0.017298    6.917e+02      0.000000
       7    0.111950   -0.017298    7.304e+01      0.000001
       8    0.111958   -0.017301    6.916e+02      0.000000
       9    0.111958   -0.017301    7.303e+01      0.000001
      10    0.111967   -0.017305    6.916e+02      0.000000
      11    0.111967   -0.017305    7.302e+01      0.000001
      12    0.111976   -0.017309    6.915e+02      0.000000
      13    0.111976   -0.017308    7.301e+01      0.000001
      14    0.111984   -0.017312    6

C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\837523664.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun = 0.5 * float(r.T @ r) + l*float(w.T @ w)
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\837523664.py:13: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\837523664.py:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  t = fl

     135    0.112505   -0.017524    7.254e+01      0.000001
     136    0.112513   -0.017527    6.869e+02      0.000000
     137    0.112513   -0.017527    7.253e+01      0.000001
     138    0.112522   -0.017531    6.869e+02      0.000000
     139    0.112522   -0.017531    7.253e+01      0.000001
     140    0.112530   -0.017534    6.868e+02      0.000000
     141    0.112531   -0.017534    7.252e+01      0.000001
     142    0.112539   -0.017538    6.867e+02      0.000000
     143    0.112539   -0.017538    7.251e+01      0.000001
     144    0.112548   -0.017541    6.867e+02      0.000000
     145    0.112548   -0.017541    7.250e+01      0.000001
     146    0.112556   -0.017545    6.866e+02      0.000000
     147    0.112556   -0.017545    7.250e+01      0.000001
     148    0.112565   -0.017548    6.865e+02      0.000000
     149    0.112565   -0.017548    7.249e+01      0.000001
     150    0.112573   -0.017552    6.864e+02      0.000000
     151    0.112574   -0.017552    7.24

In [69]:
r_final = eX @ w_star_l2 - y_train
fun_final =0.5 * float(r_final.T @ r_final) + l * float(w_star_l2.T @ w_star_l2)
grad_final = eX.T @ r_final + 2*l*w_star_l2
norm_final = np.linalg.norm(grad_final)

C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\1156242029.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun_final =0.5 * float(r_final.T @ r_final) + l * float(w_star_l2.T @ w_star_l2)


In [70]:
w_np, *_ = np.linalg.lstsq(eX, y_train, rcond=None)
w_np

array([[ 1.41263433e+02],
       [ 4.56150240e-02],
       [-1.83677944e+00],
       [-1.39416975e-02],
       [ 7.77026591e-02],
       [-7.78341270e-02],
       [ 4.53354375e-03],
       [-1.29184420e-04],
       [-1.41538715e+02],
       [ 6.84121810e-01],
       [ 6.88495142e-01],
       [ 2.25839398e-01]])

In [71]:
Q = eX.T @ eX + 2*l*I
eigvals = np.linalg.eigvalsh(Q)
kappa = eigvals.max() / eigvals.min()
rho = ((kappa-1)/(kappa+1))**2
rho

0.9999995935960813

In [72]:
w_star_l2, rho, f"{runtime_l2:.4f}", f"{fun_final:.4f}", f"{norm_final:.4f}"

(array([[ 0.12917486],
        [-0.02364404],
        [-0.43904426],
        [ 0.05005643],
        [ 0.02367698],
        [-0.00575153],
        [ 0.00812824],
        [-0.00150417],
        [ 0.12709856],
        [ 0.46669984],
        [ 0.21219436],
        [ 0.38834007]]),
 0.9999995935960813,
 '6.7642',
 '1300.4623',
 '561.8948')

In [73]:
w_star = w_star_l2
y_pred_train = eX @ w_star

eX_test = np.hstack([np.ones((X_test.shape[0], 1)), X_test])
y_pred_test = eX_test @ w_star

mae_train = np.mean(np.abs(y_train - y_pred_train))
mae_test = np.mean(np.abs(y_test - y_pred_test))
mae_train, mae_test

(0.6080443472449191, 0.5575577195836374)

## 5.

In [67]:
from tabulate import tabulate

table = [
    ["Runtime (s)",                 8.5956,  6.4184],
    ["Number of Iterations",        5000,  5000],
    ["Objective Function Value",    1326.2278, 1310.3519],
    ["Norm of Gradient",            1000.7734, 691.9329],
    ["Mean Absolute Error (Train)", 0.6155,  0.6109],
    ["Mean Absolute Error (Test)",  0.5678,  0.5612],
]

print(tabulate(table, headers=["Metric", "Basic Model", "L2 Regularization"], tablefmt="grid"))


+-----------------------------+---------------+---------------------+
| Metric                      |   Basic Model |   L2 Regularization |
+=============================+===============+=====================+
| Runtime (s)                 |        8.5956 |              6.4184 |
+-----------------------------+---------------+---------------------+
| Number of Iterations        |     5000      |           5000      |
+-----------------------------+---------------+---------------------+
| Objective Function Value    |     1326.23   |           1310.35   |
+-----------------------------+---------------+---------------------+
| Norm of Gradient            |     1000.77   |            691.933  |
+-----------------------------+---------------+---------------------+
| Mean Absolute Error (Train) |        0.6155 |              0.6109 |
+-----------------------------+---------------+---------------------+
| Mean Absolute Error (Test)  |        0.5678 |              0.5612 |
+-------------------

## 6.

Overall, the L2-regularized model performed better in terms of final accuracy and runtime. It attained a lower final objective function value and gradient norm (meaning the final attained point's steepest direction was less steep), and had marginally better (although small) MAE scores on both the train and test datasets. This matches both what is expected theoretically and also the preliminary conclusion reached by comparing the convergence rates (L2-regularized was lower). Adding the L2 term improves the conditioning of the matrix, smoothing out the surface.