# MA 3236 Computer Assignment - Jiasheng Zhou

## 1.

For a function in quadratic form $q(w) = \frac12x^TQx+b^Tx+c$, $q(w)$ is convex iff $Q$ is PSD, and is strictly convex when $Q$ is PD. expanding $f(w)$:
$$
\begin{align}
f(w) &= \frac12||(e\:X)w-y||^2 \\
&= \frac12((e\:X)w-y)^T((e\:X)w-y) \\
&= \frac12(w^T(e\:X)^T-y^T)((e\:X)w-y) \\
&= \frac12(w^T(e\:X)^T(e\:X)w) -y^T(e\:X)w +\frac12y^Ty.
\end{align}
$$
As $w^T(e\:X)^T(e\:X)w = ((e\:X)w)^T((e\:X)w) = ||(e\:X)w||^2 \geq 0$, $\forall w \in \mathbb{R}^{p+1}$, $Q=(e\:X)^T(e\:X)$ is PSD and thus $f(w)$ is conve\:X.

To ensure $Q$ is PD, we would need $((e\:X)w)^T((e\:X)w) = ||(e\:X)w||^2 > 0$ for all $w \neq 0$. This requirement is the definition of linear independence, so we must have $e\:X$ be linearly independent. This occurs when $X$ is linearly independent and $e$ is not a linear combination of the columns of $X$. 

It is almost certain that the wine dataset satisfies this condition. As there is a positive amount of variance with the values for each column, it isn't possible that one entire column is constant (multiple of $e$). Moreover, it is extremely unlikely that there is a linear combination of columns that results in a constant column, since each value's range is continuous, and there are over 4000 observations. 

## 2.

Let $t_k$ be step size at $k$th iteration. Then

$$
\begin{align}
t_k &= \text{arg min}_t(f(w^{(k)}-t\nabla_k) \\
&= \text{arg min}_t(\frac12||(e\:X)w^{(k)}-y-t(e\:X)\nabla_k||^2)
\end{align}
$$

To find the minimum, we take the derivative of $f$ w.r.t. to $t$ and find the zeros:
$$
\begin{align}
0 &= \frac{d}{dt}(\frac12||(e\:X)w^{(k)}-y-t(e\:X)\nabla_k||^2) \\
&= ((e\:X)w^{(k)}-y-t(e\:X)\nabla_k)^T((e\:X)\nabla_k) \\
\end{align}
$$
Solving,
$$
\begin{align}
t((e\:X)\nabla_k)^T(e\:X)\nabla_k &= ((e\:X)w^{(k)}-y)^T(e\:X)\nabla_k \\
t\nabla_k^T(e\:X)^T(e\:X)\nabla_k &= ((e\:X)^T((e\:X)w^{(k)}-y))^T\nabla_k \\
t &= \frac{(\nabla_k)^T\nabla_k}{\nabla_k^T(e\:X)^T(e\:X)\nabla_k}
\end{align}
$$
To arrive at the final line above, note that $\nabla_k = (e\:X)^T(e\:X)w^{(k)}-(e\:X)^Ty$, which we substitute into the numerator.

## 3.

note: I couldn't find the preprocessed files mentioned on the assignment writeup on Canvas (Xytrain.csv, Xytest.csv) so I downloaded the dataset directly from the link provided

In [81]:
import numpy as np
import time

data = np.loadtxt("winequality-white.csv", delimiter=';', skiprows=1)
X = data[:, :-1]
y = data[:, -1:].reshape(-1, 1)

X_train, X_test = X[:4298], X[4298:]
y_train, y_test = y[:4298], y[4298:]

In [82]:
n, p = X_train.shape
e = np.ones((n, 1))
eX = np.hstack([e, X_train])

w = np.zeros((p + 1, 1))
tolerance = 1e-6
iter = 5000

In [83]:
#printing only first 10 iterations to avoid clutter in final submission

print("\n    iter     w[0]         w[1]       ||grad||      step-len")
print("-------------------------------------------------------------")
start = time.time()
for i in range(iter):
    r = eX @ w - y_train
    fun = 0.5 * float(r.T @ r)
    grad = eX.T @ r
    d = -grad
    normd = np.linalg.norm(d)
    if(i<10):
        print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
    if(np.linalg.norm(grad) < tolerance):
        break
    t = float((grad.T @ grad) / (grad.T @ eX.T @ eX @ grad))
    if(i<10):
        print(f"   {t:11.6f}")
    w = w + t*d
end = time.time()
w_star = w
runtime = end-start


    iter     w[0]         w[1]       ||grad||      step-len
-------------------------------------------------------------
       0    0.000000    0.000000    3.630e+06      0.000000
       1    0.000257    0.001774    3.537e+04      0.000010
       2    0.022682    0.149709    3.302e+05      0.000000
       3    0.022709    0.149891    2.977e+04      0.000001
       4    0.023068    0.152065    1.786e+05      0.000000
       5    0.023085    0.152175    1.645e+04      0.000001
       6    0.023437    0.154192    1.046e+05      0.000000
       7    0.023449    0.154266    1.010e+04      0.000001
       8    0.023805    0.156234    7.246e+04      0.000000
       9    0.023815    0.156291    7.427e+03      0.000001


C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\1620201140.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun = 0.5 * float(r.T @ r)
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\1620201140.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\1620201140.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  t = float((grad.T @ gr

In [84]:
w_star

array([[ 8.20124211e-02],
       [-4.38510702e-03],
       [-1.53424677e-01],
       [ 2.11144160e-02],
       [ 2.42496687e-02],
       [ 1.77381096e-04],
       [ 8.59630599e-03],
       [-1.10075414e-03],
       [ 8.10777256e-02],
       [ 3.23995972e-01],
       [ 1.00988256e-01],
       [ 4.18906798e-01]])

In [85]:
r_final = eX @ w_star - y_train
fun_final = 0.5 * float(r_final.T @ r_final)
grad_final = eX.T @ r_final
norm_final = np.linalg.norm(grad_final)

C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\417156451.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun_final = 0.5 * float(r_final.T @ r_final)


In [86]:
Q = eX.T @ eX
eigvals = np.linalg.eigvalsh(Q)
kappa = eigvals.max() / eigvals.min()
rho = ((kappa-1)/(kappa+1))**2

In [87]:
w_star, rho, f"{runtime:.4f}", f"{fun_final:.4f}", f"{norm_final:.4f}"

(array([[ 8.20124211e-02],
        [-4.38510702e-03],
        [-1.53424677e-01],
        [ 2.11144160e-02],
        [ 2.42496687e-02],
        [ 1.77381096e-04],
        [ 8.59630599e-03],
        [-1.10075414e-03],
        [ 8.10777256e-02],
        [ 3.23995972e-01],
        [ 1.00988256e-01],
        [ 4.18906798e-01]]),
 0.9999999999701643,
 '8.0444',
 '1326.2278',
 '1000.7734')

In [88]:
y_pred_train = eX @ w_star

eX_test = np.hstack([np.ones((X_test.shape[0], 1)), X_test])
y_pred_test = eX_test @ w_star

mae_train = np.mean(np.abs(y_train - y_pred_train))
mae_test = np.mean(np.abs(y_test - y_pred_test))
mae_train, mae_test

(0.615454082643502, 0.567879079111807)

## 4.

In [89]:
l = 5
I = np.eye(p+1)

print("\n    iter     w[0]         w[1]       ||grad||      step-len")
print("-------------------------------------------------------------")
start = time.time()
for i in range(iter):
    r = eX @ w - y_train
    fun = 0.5 * float(r.T @ r) + l*float(w.T @ w)
    grad = eX.T @ r + 2*l*w
    d = -grad
    normd = np.linalg.norm(d)
    if(i<10):
        print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
    if(np.linalg.norm(grad) < tolerance):
        break
    t = float((grad.T @ grad) / (grad.T @ (eX.T @ eX + 2.0 *l * I) @ grad))
    if(i<10):
        print(f"   {t:11.6f}")
    w = w + t*d
end = time.time()
w_star_l2 = w
runtime_l2 = end-start

C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\4113381174.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun = 0.5 * float(r.T @ r) + l*float(w.T @ w)
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\4113381174.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"{i:8d} {float(w[0]):11.6f} {float(w[1]):11.6f} {normd:12.3e}", end="")
C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\4113381174.py:17: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  t =


    iter     w[0]         w[1]       ||grad||      step-len
-------------------------------------------------------------
       0    0.082012   -0.004385    1.000e+03      0.000000
       1    0.082013   -0.004385    1.056e+02      0.000001
       2    0.082028   -0.004393    9.998e+02      0.000000
       3    0.082029   -0.004393    1.056e+02      0.000001
       4    0.082044   -0.004401    9.995e+02      0.000000
       5    0.082045   -0.004401    1.055e+02      0.000001
       6    0.082060   -0.004409    9.992e+02      0.000000
       7    0.082061   -0.004409    1.055e+02      0.000001
       8    0.082076   -0.004417    9.989e+02      0.000000
       9    0.082077   -0.004416    1.055e+02      0.000001


In [90]:
r_final = eX @ w_star_l2 - y_train
fun_final =0.5 * float(r_final.T @ r_final) + l * float(w_star_l2.T @ w_star_l2)
grad_final = eX.T @ r_final + 2*l*w_star_l2
norm_final = np.linalg.norm(grad_final)

C:\Users\jiash\AppData\Local\Temp\ipykernel_22924\1156242029.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  fun_final =0.5 * float(r_final.T @ r_final) + l * float(w_star_l2.T @ w_star_l2)


In [91]:
w_np, *_ = np.linalg.lstsq(eX, y_train, rcond=None)
w_np

array([[ 1.41263433e+02],
       [ 4.56150240e-02],
       [-1.83677944e+00],
       [-1.39416975e-02],
       [ 7.77026591e-02],
       [-7.78341270e-02],
       [ 4.53354375e-03],
       [-1.29184420e-04],
       [-1.41538715e+02],
       [ 6.84121810e-01],
       [ 6.88495142e-01],
       [ 2.25839398e-01]])

In [92]:
Q = eX.T @ eX + 2*l*I
eigvals = np.linalg.eigvalsh(Q)
kappa = eigvals.max() / eigvals.min()
rho = ((kappa-1)/(kappa+1))**2
rho

0.9999995935960813

In [93]:
w_star_l2, rho, f"{runtime_l2:.4f}", f"{fun_final:.4f}", f"{norm_final:.4f}"

(array([[ 0.11192317],
        [-0.01728713],
        [-0.30458181],
        [ 0.03768575],
        [ 0.02370543],
        [-0.00227228],
        [ 0.00834959],
        [-0.00140913],
        [ 0.11044069],
        [ 0.42572717],
        [ 0.16484961],
        [ 0.39677315]]),
 0.9999995935960813,
 '6.4052',
 '1310.3519',
 '691.9329')

In [94]:
w_star = w_star_l2
y_pred_train = eX @ w_star

eX_test = np.hstack([np.ones((X_test.shape[0], 1)), X_test])
y_pred_test = eX_test @ w_star

mae_train = np.mean(np.abs(y_train - y_pred_train))
mae_test = np.mean(np.abs(y_test - y_pred_test))
mae_train, mae_test

(0.6109421256495468, 0.56127958108676)

## 5.

In [95]:
from tabulate import tabulate

table = [
    ["Runtime (s)",                 8.5956,  6.4184],
    ["Number of Iterations",        5000,  5000],
    ["Objective Function Value",    1326.2278, 1310.3519],
    ["Norm of Gradient",            1000.7734, 691.9329],
    ["Mean Absolute Error (Train)", 0.6155,  0.6109],
    ["Mean Absolute Error (Test)",  0.5678,  0.5612],
]

print(tabulate(table, headers=["Metric", "Basic Model", "L2 Regularization"], tablefmt="grid"))


+-----------------------------+---------------+---------------------+
| Metric                      |   Basic Model |   L2 Regularization |
+=============================+===============+=====================+
| Runtime (s)                 |        8.5956 |              6.4184 |
+-----------------------------+---------------+---------------------+
| Number of Iterations        |     5000      |           5000      |
+-----------------------------+---------------+---------------------+
| Objective Function Value    |     1326.23   |           1310.35   |
+-----------------------------+---------------+---------------------+
| Norm of Gradient            |     1000.77   |            691.933  |
+-----------------------------+---------------+---------------------+
| Mean Absolute Error (Train) |        0.6155 |              0.6109 |
+-----------------------------+---------------+---------------------+
| Mean Absolute Error (Test)  |        0.5678 |              0.5612 |
+-------------------

## 6.

Overall, the L2-regularized model performed better in terms of final accuracy and runtime. It attained a lower final objective function value and gradient norm (meaning the final attained point's steepest direction was less steep), and had marginally better (although small) MAE scores on both the train and test datasets. This matches both what is expected theoretically and also the preliminary conclusion reached by comparing the convergence rates (L2-regularized was lower). Adding the L2 term improves the conditioning of the matrix, smoothing out the surface.